### ISSUE TITLE
Création du MVP - V1

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#1268]
**Objectif**

CARTES DANS LE GIT DÉDIÉ (je te laisse compléter @sbenfares )

suivi des cartes ici : https://github.com/mission-apprentissage/flux-retour-cfas/issues/1674

**Fonctionnalités à développer :**

Sprint 1 (09/08/2022 au 19/08/2022) : 
- [x] Nom de domaine à définir 09/08 https://github.com/mission-apprentissage/flux-retour-cfas/issues/1265 @sbenfares @pabloHry @cathbaiona @MelanieRAPHAEL 
- [x] Création domaine (nom de domaine, espace GitHub et de stockage, metabase, etc) à définir - @sbenfares @pabloHry - https://github.com/mission-apprentissage/flux-retour-cfas/issues/1266 
- [x] Création des serveurs @sbenfares @pabloHry
- [x] Création de compte @sbenfares @pabloHry 
- Champs utilisateurs - Modèle données utilisateurs
- Permissions 
- Formulaire - specs 

- [x] Front maquette sur TdB accéder au SERP @cathbaiona @MelanieRAPHAEL 
- [x] Front maquette SERP et documentation @cathbaiona @MelanieRAPHAEL @sbenfares 
- [x] Définir les champs iso API V2 - https://github.com/mission-apprentissage/flux-retour-cfas/issues/1267 @MelanieRAPHAEL @cathbaiona 
- [x] Fichier exemple et modèle schéma de données @cathbaiona @MelanieRAPHAEL 
- [x] Maquette erreur et signalement erreur et définir les cas d'erreur - @cathbaiona @MelanieRAPHAEL @sbenfares 

Sprint 2 (du 22/08 au 02/09) : 
- [x] Tests utilisateurs fichier @cathbaiona @MelanieRAPHAEL https://github.com/mission-apprentissage/flux-retour-cfas/issues/1265 
- [x] Front intégrer l'accès TdB @sbenfares @pabloHry 
- [x] Front intégrer documentation + maquette SERP @sbenfares @pabloHry 
- [x] Déposer un fichier rempli @sbenfares @pabloHry 
- [x] J’aspire les données @sbenfares @pabloHry 
- [x] Contrôles - signaler les problèmes @sbenfares @pabloHry 
- [x] Confirmation @sbenfares @pabloHry 
- [ ] Envoi TdB par API @sbenfares @pabloHry 
- [x] Rédiger cartes pour les tests utilisateurs sur maquette sprint 3 / MVP avec front @MelanieRAPHAEL avec @cathbaiona 

**Definition of done**

- [ ] _Un CFA sans ERP peut et a transmis ses données via la fonctionnalité sans ERP_
- [ ] _Les données transmises sont cohérentes et correspondent aux champs attendus_

Notes

A voir Spécifier Préciser : 
- MVP dépôt fichier : maquette + fonctionnement IHM + formulaire de dépôt + fichier Excel champs + connecté à un metabase ? - Connecté via API au TdB ?
- Besoin de la création d'un compte ? Penser aux notifications (mails à collecter, etc)

**Cartes liées**
- EPIC correspondant : https://github.com/mission-apprentissage/flux-retour-cfas/milestone/7
