### ISSUE TITLE
Pilotage usage du TDB : Lister les éléments à tracker

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#1781]
En tant que membre de l'équipe TDB, j'ai une visibilité sur les fonctionnalités les plus actionnées par les utilisateurs.

- [x] lister les éléments trackables sur chacune des pages ( /!\ tenir compte de la nouvelle home)
- [x] définir parmi ces éléments lesquels il est intéressant de tracker et pourquoi
- [x] transmettre éléments à acm pour alimenter les specs de la page de suivi interne

Carte terminée :   

- [x] créer une carte pour la mise en place du plan de tracking

**Comment by Anne-Camille** [comment]
@ClemLan : done, repris dans https://github.com/mission-apprentissage/flux-retour-cfas/issues/1998
