### ISSUE TITLE
Réintégration tech de partage simplifié dans le TdB

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/flux-retour-cfas#2082]
**Objectif**

_Réintégrer l'architecture du projet Partage Simplifié dans le repository du TdB_

**Definition of done**

- [ ] _Intégration du model de PS dans le Tdb_
- [ ] _Intégration de la logique métier & services dans le TdB_
- [ ] _Intégration de l'UI de PS dans le Tdb_
- [ ] _Intégration des mécanismes de l'infra PS dans le TdB_
- [ ] _Intégration des mécanismes de l'infra PS dans le TdB_
- [ ] _Le répository de partage-simplifié est archivé_

**Todo Tech**

- [x] _Config & DotEnv_
- [x] _Model & unit test indexs_
- [x] _Common & Utils & Domain_
- [x] _Factories_
- [ ] _Services_
- [ ] _Mappers_
- [ ] _Http_
- [ ] _Infra Vault_
- [ ] _Infra Structure folder_
- [ ] _Infra Pwd Mongo_

**Todo Next Steps Tech**
- [ ] _Remove vars from docker-compose_
- [ ] _Upgrade_
- [ ] _ESM_
- [ ] _Refacto CI & CLI Make_
- [ ] _CRA 5_
- [ ] _Remove mongoose_
- [ ] _Remove mongoose _ add logs & refacto mongoClient & tests_
- [ ] _Refacto indexeurs_
- [ ] _Remove PS d'upttime_
