### ISSUE TITLE
Page statistiques internes : installer tracking

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2248]
Mettre en place les tracking suivants :

- [ ] Nombre de clic sur la FAQ
- [ ] Type de question de la FAQ consultées (tracking par question)
- [ ] Tracking utilisateurs qui utilisent le TDB fréquemment par période : plus de 2 connexions dans l'année l'année civil
- [ ]  Tracking utilisateurs qui utilisent le TDB fréquemment par type d'utilisateur : plus de 2 connexions dans l'année civile
- [ ] Temps passé sur chaque page (par page)
- [ ] Temps passé sur chaque page (par profil)
- [ ] canal de provenance des demandes support (MB, mail, site après FAQ, site "contacter équipe") 
- [ ]  fréquence de chargement des données via PS (à voir si tracking ou requête ??)
- [ ] Pages les plus visitées 
- [ ] Canal d'acquisition de visiteurs

Ces tracking devront ensuite faire l'objet d'une travail d'intégration front au regard des maquettes de @cathbaiona

- [ ] vérification identité pilote : récupérer la liste de tous les comptes Dreets et Deets. Système d'alerte à installer lorsque le mail ne se termine pas par @dreets.gouv.fr ou deets.gouv.fr. Dans ce cas, ne pas donner accès aux données.
