### ISSUE TITLE
EPIC SIFA et SERP

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2268]
"Stuff" derrière 

- onglet "Mes effectifs" (=feature serp)
- onglet "Mon enquête" (=feature Sifa)

- [ ] Workflow : https://whimsical.com/parcours-ps-sifa-Ejb1p6zm2oro55dzX2SiLR

- [ ] Maquettes écrans : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=6196%3A167821&t=TmuUF4h7LXPGAg5E-0

- [ ] Données SERP à recueillir : ISO actuel cf mapping V1 : https://docs.google.com/spreadsheets/d/18Tx8KlqH-fBraguBKYnvi4exxKqGabSf-SqrGZfkrgI/edit#gid=0 

(WIP pour info : dans le futur, les nouveaux indicateurs nécessiteront de recueillir des données supplémentaires listées ici : https://docs.google.com/spreadsheets/d/13HJk630xVY375Bh0TY-rQcz440IrBYQTMmCIZx9xl5g/edit#gid=1634709714)

- [ ] Données SIFA à recueillir : https://docs.google.com/spreadsheets/d/1OT2X6Z1F6Ltvg49eTHM54WLFjlhL1Wzj/edit#gid=1876593718
